Graduation project: stats_module
RuslanYapparov/java-explore-with-me pull request #3
Opened 2023-08-03 22:28 UTC by RuslanYapparov

2023-08-04 22:29 UTC, sergeymamonov requested changes
Удалить все лишние гитигноры.

2023-08-04 22:29 UTC, sergeymamonov commented on stats_service/server_submodule/src/main/java/ru/practicum/explore_with_me/stats_service/server_submodule/service/StatsServiceImpl.java
> +        if (ipUnique == null || ipUnique == false) {
ipUnique - это логическая переменная, поэтому можно вместо ipUnique == false записать !ipUnique

2023-08-04 22:29 UTC, sergeymamonov commented on stats_service/Dockerfile
Лишний докер файл.

2023-08-07 16:12 UTC, RuslanYapparov commented on stats_service/Dockerfile
Убрал неиспользующиеся Dockerfile

2023-08-07 16:12 UTC, RuslanYapparov commented on stats_service/server_submodule/src/main/java/ru/practicum/explore_with_me/stats_service/server_submodule/service/StatsServiceImpl.java
> +        if (ipUnique == null || ipUnique == false) {
Некоторое время пришлось потупить над логикой логических выражений в if, но в итоге понял, почему так будет работать. Заменил на упрощенный вариант с !ipUnique

2023-08-07 16:12 UTC, RuslanYapparov commented on stats_service/client_submodule/src/main/java/ru/practicum/explore_with_me/stats_service/client_submodule/client/StatsClient.java
> +    private void validateRequestParameters(String ip, String uri) {
Перенес валидацию входных данных (специфическую валидацию, не предусмотренную javax.validation), в модуль сервера статистики. В качестве валидатора создал утилитарный класс MethodParameterValidator. Чтобы можно было получить текст ошибки из валидаторов, решил возвращать из клиента объект dto с кодом 400 и полем application, содержащим текст ошибки. Переписал тесты для проверки работы валидации.

2023-08-07 16:12 UTC, RuslanYapparov commented on stats_service/.gitignore
> +target/
Удалены все файлы gitignore кроме лежащего в корне проекта.

2023-08-07 16:14 UTC, RuslanYapparov commented on main_service/.gitignore
> +target/
Удалены все файлы gitignore кроме лежащего в корне проекта.

2023-08-07 20:17 UTC, sergeymamonov approved these changes

2023-08-08 05:02 UTC, merged