Graduation project: main_module
RuslanYapparov/java-explore-with-me pull request #4
Opened 2023-08-19 20:51 UTC by RuslanYapparov

Реализовал необходимые функциональности основного сервиса, протестировал основные классы-сервисы и контроллеры (для оставшихся функциональностей запросов на участие и подборок дополню тесты позднее).

2023-08-20 20:01 UTC, sergeymamonov requested changes

2023-08-21 07:43 UTC, RuslanYapparov commented on main_service/src/main/java/ru/practicum/explore_with_me/main_service/controller/ExploreWithMeExceptionHandler.java
> +                .status(HttpStatus.FORBIDDEN) // В соответствии со спецификацией, в поле статус должно быть это значение
Тесты проверяют только статус-код ответа сервера, значение этого поля не проверятся. 
Поля ErrorResponse с примерами для каждого вида исключения приведены в спецификации API для Swagger, подготовленной  разработчиками курса для дипломного проекта: https://raw.githubusercontent.com/yandex-praktikum/java-explore-with-me/main/ewm-main-service-spec.json (или соответствующий файл, лежащий в корне проекта, пример можно увидеть в описании функционала событий). 
Проанализировал использование исключения и понял, что в моем случае оно имеет неправильное название - исключение применяется в случаях запрета на проведение операций создания/изменения сущности event (я также использовал по смыслу для некоторых операций с сущностью request, хотя в спецификации они не отражены, но в тестах ожидается именно 409 код). Для других сущностей характерны только DataIntegrityViolationException с кодом ответа 409 и значением поля status 'CONFLICT'.
Переименовал исключение в ObjectModificationException

2023-08-21 12:51 UTC, RuslanYapparov commented on main_service/src/main/java/ru/practicum/explore_with_me/main_service/controller/ExploreWithMeExceptionHandler.java
> +                .status(HttpStatus.SERVICE_UNAVAILABLE)
Вроде очевидное несоответствие, не понимаю, как не заметил его и пропустил на тестах. Исправил на INTERNAL_SERVER_ERROR.

2023-08-21 12:51 UTC, RuslanYapparov commented on main_service/src/main/java/ru/practicum/explore_with_me/main_service/controller/ExploreWithMeExceptionHandler.java
> +                exception.getRequiredType() == null ? "" : exception.getRequiredType().getSimpleName(),
Вроде пытался выработать привычку, что методы из туториалов, вроде этого, нужно прокручивать в голове на предмет "заряженных пистолетов для выстреливания в ногу", но пока она (привычка или голова)  часто не срабатывает.
Добавил проверку элементов, попадающих в строку message на null и выводом дефолтного неинформативного сообщения.

2023-08-21 12:51 UTC, RuslanYapparov commented on main_service/src/main/java/ru/practicum/explore_with_me/main_service/mapper/impl/EventMapper.java
> +    @Mapping(target = "category", expression = "java(Category.builder().id(eventRestCommand.getCategory()).build())")
Почему-то такой лаконичный способ маппинга не пришел в голову, когда столкнулся с проблемой и понадобилось указывать вручную. Значение по умолчанию для поля name не используется, а игнорирование поля происходит без указания в аннотации, поэтому оставил только аннотацию для идентификатора.

2023-08-21 12:51 UTC, RuslanYapparov commented on main_service/src/main/java/ru/practicum/explore_with_me/main_service/mapper/impl/EventMapper.java
> +public interface EventMapper extends ObjectMapper<EventEntity, Event, EventRestCommand, EventRestView> {
На предыдущем учебном проекте Вы также указывали на то, что во многих местах я усложняю код, используя наследование. Пока что не могу нащупать грань между пользой от использования и вредом от получающегося усложнения. И в том, и в этом проекте постарался снизить использование наследования, теперь кроме мапперов нигде не наследую. Преимущество вижу такое - пусть из-за того, что имеем дело с интерфейсами в снижении строк кода выигрыш небольшой, зато базовый интерфейс создает контракт с названиями методов, по которому работают все мапперы сущностей, возможно, от этого была бы польза при дальнейшем разработке приложения. Или вред. В любом случае, 4 базовых метода используются во всех классах-мапперах-потомках и в каждом классе-сервисе, поэтому хочется оставить это наследование.

2023-08-21 12:53 UTC, RuslanYapparov commented on main_service/src/main/java/ru/practicum/explore_with_me/main_service/mapper/impl/UserMapper.java
> +    UserShort mapUserShortFromUserEntity(UserEntity userEntity);
Нет... Опять забыл удалить после изменения логики в сервисе, неудобно вышло.

2023-08-21 12:59 UTC, RuslanYapparov commented on main_service/src/main/java/ru/practicum/explore_with_me/main_service/mapper/impl/EventMapper.java
> +            expression = "java(java.time.LocalDateTime.parse(eventRestCommand.getEventDate(), FORMATTER))")
Согласен, получилось более лаконично

2023-08-22 04:22 UTC, sergeymamonov approved these changes

2023-08-22 04:22 UTC, sergeymamonov commented on main_service/src/main/java/ru/practicum/explore_with_me/main_service/mapper/impl/EventMapper.java
> +public interface EventMapper extends ObjectMapper<EventEntity, Event, EventRestCommand, EventRestView> {
В данном случае это немного надуманный базовый класс. Общего функционала интерфейсам наследникам он не дает. Вы просто хотите, чтобы во всех интерфейсах методы назывались одинаково. То есть пока, кроме названий методов все эти интерфейсы ничего не связывает. Преждевременная оптимизация и универсализм - это не то, к чему нужно стремиться.

2023-08-22 04:22 UTC, sergeymamonov commented on main_service/src/main/java/ru/practicum/explore_with_me/main_service/mapper/impl/UserMapper.java
> +public interface UserMapper extends ObjectMapper<UserEntity, User, UserRestCommand, UserRestView> {
А зачем тогда остается интерфейс без методов?

2023-08-22 06:41 UTC, merged